<?php

namespace InventoryBundle\Repository;

/**
 * ManageOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManageOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
