<?php

namespace InventoryBundle\Repository;

/**
 * OptionValuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionValuesRepository extends \Doctrine\ORM\EntityRepository
{
}
