<?php

namespace InventoryBundle\Repository;

/**
 * PopItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PopItemRepository extends \Doctrine\ORM\EntityRepository
{
}
