<?php

namespace InventoryBundle\Repository;

/**
 * ProductSpecificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSpecificationRepository extends \Doctrine\ORM\EntityRepository
{
}
