<?php

namespace InventoryBundle\Repository;

/**
 * PromoKitOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoKitOrdersRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductVariants() {

    }
}
