<?php

namespace InventoryBundle\Repository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;
use InventoryBundle\Entity\Channel;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * PromoKitOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoKitOrdersRepository extends EntityRepository
{
    public function getProductVariants(Channel $channel, $warehouseName) {
        $warehouse = $this->getEntityManager()->getRepository('WarehouseBundle:Warehouse')->findOneBy(array('name' => $warehouseName));
        $products = array();

        foreach($warehouse->getInventory() as $item)
            foreach($item->getProductVariant()->getProduct()->getChannels() as $c)
                if($c->getId() == $channel->getId())
                    $products[] = $item->getProductVariant();

        return $products;
    }

    public function getActivePromoKitItems() {
        return $this->getEntityManager()->getRepository('InventoryBundle:PromoKit')->findBy(array('active' => true));
    }
}
