<?php

namespace InventoryBundle\Repository;

/**
 * PromoKitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoKitRepository extends \Doctrine\ORM\EntityRepository
{
}
