<?php

namespace InventoryBundle\Repository;

/**
 * RebateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RebateRepository extends \Doctrine\ORM\EntityRepository
{
}
