<?php

namespace InventoryBundle\Repository;
use InventoryBundle\Entity\Warehouse;

/**
 * WarehouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarehouseRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Returns the number of total items in the warehouse
     *
     * @param Warehouse $warehouse
     * @return int
     */
    public function getWarehouseInventory(Warehouse $warehouse)
    {
        if(count($warehouse->getInventory()) == 0)
            return 0;

        $quantity = 0;
        foreach($warehouse->getInventory() as $item)
            $quantity += $item->getQuantity();

        return $quantity;
    }

    public function getAllWarehousesArray() {

}

}
