<?php

namespace InventoryBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * WarrantyClaimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarrantyClaimRepository extends EntityRepository
{
}
