<?php

namespace InventoryBundle\Repository;

/**
 * WarrantyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarrantyRepository extends \Doctrine\ORM\EntityRepository
{
}
