services:
#    inventory.example:
#        class: InventoryBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  form.type.warrantyclaim:
        class: InventoryBundle\Form\WarrantyClaimType
        arguments: ["@security.token_storage", "@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: warrantyclaim_type }