<?php

namespace AppBundle\Repository;

/**
 * PriceGroupPricesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceGroupPricesRepository extends \Doctrine\ORM\EntityRepository
{
}
