<?php

namespace AppBundle\Repository;

/**
 * RoutePermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoutePermissionRepository extends \Doctrine\ORM\EntityRepository
{
}
