<?php

namespace AppBundle\Repository;

/**
 * SettingSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
