website_homepage:
    path:     /{site}
    defaults: { _controller: WebsiteBundle:Website:index }
    requirements:
        site: mlily|bedboss

mattresses:
    path:     /{site}/mattresses
    defaults: { _controller: WebsiteBundle:Website:mattressIndex }
    requirements:
        site: mlily|bedboss

single_mattresses:
    path:     /{site}/mattresses/{id}
    defaults: { _controller: WebsiteBundle:Website:singleMattressIndex }
    requirements:
        site: mlily|bedboss
        id: '\d+'

pillows:
    path:     /{site}/pillows
    defaults: { _controller: WebsiteBundle:Website:pillowsIndex }
    requirements:
        site: mlily|bedboss

adjustables:
    path:     /{site}/adjustables
    defaults: { _controller: WebsiteBundle:Website:adjustablesIndex }
    requirements:
        site: mlily|bedboss