website_homepage:
    path:     /
    defaults: { _controller: WebsiteBundle:Website:index }

mattresses:
    path:     /mattresses
    defaults: { _controller: WebsiteBundle:Website:mattressIndex }

single_mattresses:
    path:     /mattresses/{id}
    defaults: { _controller: WebsiteBundle:Website:singleMattressIndex }
    requirements:
        id: '\d+'

pillows:
    path:     /pillows
    defaults: { _controller: WebsiteBundle:Website:pillowsIndex }

adjustables:
    path:     /adjustables
    defaults: { _controller: WebsiteBundle:Website:adjustablesIndex }

web_faq:
    path:     /faq
    defaults: { _controller: WebsiteBundle:Website:faqIndex }

web_contact:
    path:     /contact
    defaults: { _controller: WebsiteBundle:Website:contactIndex }

web_product_features:
    path:     /product-features
    defaults: { _controller: WebsiteBundle:Website:productFeaturesIndex }

web_retailers:
    path:     /retailer
    defaults: { _controller: WebsiteBundle:Website:retailerIndex }

web_warranty:
    path:     /contact
    defaults: { _controller: WebsiteBundle:Website:warrantyIndex }

web_terms:
    path: /mlily-advertising-policy-terms-and-conditions
    defaults: { _controller: WebsiteBundle:Website:termsIndex }
api_submit_contact_form:
    path: /api/api_submit_contact_form
    defaults: {_controller: AppBundle:API/Website:submitContactForm }