website_homepage:
    path:     /
    defaults: { _controller: WebsiteBundle:Website:index }
    requirements:
        site: mlily|bedboss

mattresses:
    path:     /mattresses
    defaults: { _controller: WebsiteBundle:Website:mattressIndex }
    requirements:
        site: mlily|bedboss

single_mattresses:
    path:     /mattresses/{id}
    defaults: { _controller: WebsiteBundle:Website:singleMattressIndex }
    requirements:
        site: mlily|bedboss
        id: '\d+'

pillows:
    path:     /pillows
    defaults: { _controller: WebsiteBundle:Website:pillowsIndex }
    requirements:
        site: mlily|bedboss

adjustables:
    path:     /adjustables
    defaults: { _controller: WebsiteBundle:Website:adjustablesIndex }
    requirements:
        site: mlily|bedboss

web_faq:
    path:     /faq
    defaults: { _controller: WebsiteBundle:Website:faqIndex }
    requirements:
        site: mlily|bedboss

web_contact:
    path:     /contact
    defaults: { _controller: WebsiteBundle:Website:contactIndex }
    requirements:
        site: mlily|bedboss

web_product_features:
    path:     /product-features
    defaults: { _controller: WebsiteBundle:Website:productFeaturesIndex }
    requirements:
        site: mlily|bedboss

web_retailers:
    path:     /retailer
    defaults: { _controller: WebsiteBundle:Website:retailerIndex }
    requirements:
        site: mlily|bedboss

web_warranty:
    path:     /contact
    defaults: { _controller: WebsiteBundle:Website:warrantyIndex }
    requirements:
        site: mlily|bedboss

web_policy:
    path:     /mlily-advertising-policy-terms-and-conditions
    defaults: { _controller: WebsiteBundle:Website:policyIndex }
    requirements:
        site: mlily|bedboss