imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: global_config.yml }
    - { resource: "@InventoryBundle/Resources/config/services.yml" }
    - { resource: "@QuickbooksBundle/Resources/config/services.yml" }
    - { resource: "@OrderBundle/Resources/config/services.yml" }
    - { resource: "@WarehouseBundle/Resources/config/services.yml" }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@ReportBundle/Resources/config/services.yml" }


fos_js_routing:
    routes_to_expose: ['purchaseorder_show', 'purchaseorder_new', 'stockadjustment_show', 'stockadjustment_new', 'order_products_review', 'api_monthly_report']