inventory_pop_item:
    resource: "@InventoryBundle/Controller/PopItemController.php"
    type:     annotation

quickbooks:
    resource: "@QuickbooksBundle/Controller/"
    type:     annotation
    prefix:   /qb

inventory:
    resource: "@InventoryBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
_user_bundle:
    resource: "@AppBundle/Resources/config/routing.yml"
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /admin/role