inventory_purchase_order:
    resource: "@InventoryBundle/Controller/PurchaseOrderController.php"
    type:     annotation

inventory_stock_transfer:
    resource: "@InventoryBundle/Controller/StockTransferController.php"
    type:     annotation

inventory_stock_adjustment:
    resource: "@InventoryBundle/Controller/StockAdjustmentController.php"
    type:     annotation

inventory_status:
    resource: "@InventoryBundle/Controller/StatusController.php"
    type:     annotation

inventory_rebate_submission:
    resource: "@InventoryBundle/Controller/RebateSubmissionController.php"
    type:     annotation

inventory_rebate:
    resource: "@InventoryBundle/Controller/RebateController.php"
    type:     annotation

inventory_warranty_claim:
    resource: "@InventoryBundle/Controller/WarrantyClaimController.php"
    type:     annotation

inventory_promo_kit:
    resource: "@InventoryBundle/Controller/PromoKitController.php"
    type:     annotation

inventory_pop_item:
    resource: "@InventoryBundle/Controller/PopItemController.php"
    type:     annotation

quickbooks:
    resource: "@QuickbooksBundle/Controller/"
    type:     annotation
    prefix:   /qb

inventory:
    resource: "@InventoryBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
_user_bundle:
    resource: "@AppBundle/Resources/config/routing.yml"
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /admin/role

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"