# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
     authentication.handler.login_success_handler:
         class:  AppBundle\Security\LoginSuccessHandler
         arguments:  ['@router', '@security.authorization_checker']

     app.form.registration:
         class: AppBundle\Form\RegistrationFormType
         tags:
             - { name: "form.type", alias: "app_user_registration" }

     app.form.profile:
         class: AppBundle\Form\ProfileFormType
         tags:
            - { name: "form.type", alias: "app_user_profile" }

     app.form.group:
              class: AppBundle\Form\GroupFormType
              tags:
                 - { name: "form.type", alias: "app_admin_add_group" }

     app.tokens.action_listener:
        class: AppBundle\EventListener\TokenListener
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            token_storage: "@security.token_storage"
            templating: "@templating"
            router: "@router"
            session: "@session"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        scope: request