<?php

namespace OrderBundle\Repository;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * LedgerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LedgerRepository extends EntityRepository
{
    /**
     * @param User $user
     * @return array|\OrderBundle\Entity\Ledger[]
     */
    public function findByUser(User $user) {
        $em = $this->getEntityManager();
        $user_ids = array();
        $user_ids[$user->getId()] = $user->getId();
        $ledgers = array();

        $data = $em->getRepository('OrderBundle:Ledger')->findBy(array('submittedForUser' => $user));
        foreach($data as $item)
            $ledgers[] = $item;

        if($user->hasRole('ROLE_ADMIN') || $user->hasRole('ROLE_WAREHOUSE')) {
            $ledgers = $em->getRepository('OrderBundle:Ledger')->findAll();
        }
        else {

            if($user->hasRole('ROLE_DISTRIBUTOR')) {
                foreach($user->getRetailers() as $retailer) {
                    if(!isset($user_ids[$retailer->getId()])) {
                        $user_ids[$retailer->getId()] = $retailer->getId();
                        $data = $em->getRepository('OrderBundle:Ledger')->findBy(array('submittedForUser' => $retailer));
                        foreach($data as $item)
                            $ledgers[] = $item;
                    }
                }
            }
            if($user->hasRole('ROLE_SALES_REP')){
                foreach($user->getDistributors() as $distributor) {
                    if(!isset($user_ids[$distributor->getId()])) {
                        $user_ids[$distributor->getId()] = $distributor->getId();
                        $data = $em->getRepository('OrderBundle:Ledger')->findBy(array('submittedForUser' => $distributor));
                        foreach($data as $item)
                            $ledgers[] = $item;
                    }
                    foreach($distributor->getRetailers() as $retailer) {
                        if(!isset($user_ids[$retailer->getId()])) {
                            $user_ids[$retailer->getId()] = $retailer->getId();
                            $data = $em->getRepository('OrderBundle:Ledger')->findBy(array('submittedForUser' => $retailer));
                            foreach($data as $item)
                                $ledgers[] = $item;
                        }
                    }
                }
            }
            if($user->hasRole('ROLE_SALES_MANAGER')) {
                foreach($user->getSalesReps() as $salesRep) {
                    if(!isset($user_ids[$salesRep->getId()])) {
                        $user_ids[$salesRep->getId()] = $salesRep->getId();
                        $data = $em->getRepository('OrderBundle:Ledger')->findBy(array('submittedForUser' => $salesRep));
                        foreach($data as $item)
                            $ledgers[] = $item;
                    }
                    foreach($salesRep->getDistributors() as $distributor) {
                        if(!isset($user_ids[$distributor->getId()])) {
                            $user_ids[$distributor->getId()] = $distributor->getId();
                            $data = $em->getRepository('OrderBundle:Ledger')->findBy(array('submittedForUser' => $distributor));
                            foreach($data as $item)
                                $ledgers[] = $item;
                        }
                        foreach($distributor->getRetailers() as $retailer) {
                            if(!isset($user_ids[$retailer->getId()])) {
                                $user_ids[$retailer->getId()] = $retailer->getId();
                                $data = $em->getRepository('OrderBundle:Ledger')->findBy(array('submittedForUser' => $retailer));
                                foreach($data as $item)
                                    $ledgers[] = $item;
                            }
                        }
                    }
                }

            }
        }
        return $ledgers;
    }
}
