<?php

namespace OrderBundle\Repository;
use OrderBundle\Entity\Orders;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{
    public function setWarehouseDataForOrder(Orders $order) {
        foreach($order->getProductVariants() as $productVariant) {
            $i = 1;
        }
    }
}
