<?php

namespace OrderBundle\Repository;

/**
 * OrderProductVariantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersProductVariantRepository extends \Doctrine\ORM\EntityRepository
{
}
