services:
    email_service:
        class: AppBundle\Services\EmailService
        arguments: ["@swiftmailer.mailer"]
    settings_service:
        class: AppBundle\Services\SettingsService
        arguments: ["@doctrine.orm.default_entity_manager"]
