services:
    email_service:
        class: AppBundle\Services\EmailService
        arguments: ["@swiftmailer.mailer", "@service_container"]
    settings_service:
        class: AppBundle\Services\SettingsService
        arguments: ["@doctrine.orm.default_entity_manager"]
    core.extension:
        class: AppBundle\Twig\CoreExtensions
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension  }
    form.type.edituser:
        class: AppBundle\Form\EditUserSettingsType
        arguments: ["@security.token_storage", "@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: edituser_type }
    form.type.user:
        class: AppBundle\Form\UserType
        arguments: ["@security.token_storage", "@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: edituser_type }
    form.type.pricegroup:
        class: AppBundle\Form\PriceGroupType
        arguments: ["@security.token_storage", "@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: edituser_type }