services:
#    order.example:
#        class: OrderBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    order.ledger:
        class: OrderBundle\Services\LedgerService
        arguments: ["@service_container"]
    form.type.creditrequest:
        class: OrderBundle\Form\CreditRequestType
        arguments: ["@security.token_storage", "@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: creditrequest_type }