services:
#    order.example:
#        class: OrderBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    order.ledger:
        class: OrderBundle\Services\LedgerService
        arguments: ["@service_container"]