<?php

namespace WarehouseBundle\Repository;

/**
 * PurchaseOrderProductVariantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseOrderProductVariantRepository extends \Doctrine\ORM\EntityRepository
{
}
