<?php

namespace WarehouseBundle\Repository;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStatusByName($name) {
        $em = $this->getManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare("SELECT id FROM status WHERE name = :name");
        $statement->bindValue('name', $name);
        $statement->execute();
        $status_id = $statement->fetch();
        $status = $em->getRepository('WarehouseBundle:Status')->find($status_id['id']);

        return $status;
    }


}
