<?php

namespace WarehouseBundle\Repository;
use InventoryBundle\Entity\Channel;
use WarehouseBundle\Entity\PurchaseOrder;
use WarehouseBundle\Entity\StockTransfer;
use WarehouseBundle\Entity\Warehouse;

/**
 * StockTransferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockTransferRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCartArray(StockTransfer $stockTransfer)
    {
        $em = $this->getEntityManager();

        $cart = array();
        $total = 0;
        foreach($stockTransfer->getProductvariants() as $variant) {
            $image_url = '/';
            foreach($variant->getProductVariant()->getProduct()->getImages() as $image) {
                $image_url .= $image->getWebPath();
                break;
            }

            if($stockTransfer->getStatus()->getName() === 'Completed') {
                $dwq = $variant->getDepartingWarehouseQuantityAfter();
                $rwq = $variant->getReceivingWarehouseQuantityAfter();
            }
            else {
                $connection = $em->getConnection();
                $statement = $connection->prepare("SELECT COALESCE(sum(quantity),0) as total FROM warehouse_inventory WHERE product_variant_id = :product_variant_id and warehouse_id = :warehouse_id");
                $statement->bindValue('product_variant_id', $variant->getProductVariant()->getId());
                $statement->bindValue('warehouse_id', $stockTransfer->getDepartingWarehouse()->getId());
                $statement->execute();
                $departing_warehouse_quantity = $statement->fetch();
                $dwq = $departing_warehouse_quantity['total'] - $variant->getQuantity();

                $connection = $em->getConnection();
                $statement = $connection->prepare("SELECT COALESCE(sum(quantity),0) as total FROM warehouse_inventory WHERE product_variant_id = :product_variant_id and warehouse_id = :warehouse_id");
                $statement->bindValue('product_variant_id', $variant->getProductVariant()->getId());
                $statement->bindValue('warehouse_id', $stockTransfer->getReceivingWarehouse()->getId());
                $statement->execute();
                $receiving_warehouse_quantity = $statement->fetch();
                $rwq = $receiving_warehouse_quantity['total'] + $variant->getQuantity();
            }


            $total += $variant->getQuantity();

            $cart[] = array(
                'name' => $variant->getProductVariant()->getProduct()->getName().": ".$variant->getProductVariant()->getName(),
                'id' => $variant->getProductVariant()->getId(),
                'stock_transfer_product_variant_id' => $variant->getId(),
                'image_url' => $image_url,
                'quantity' => $variant->getQuantity(),
                'departing_warehouse_quantity' => $dwq,
                'receiving_warehouse_quantity' => $rwq
            );
        }
        return array(
            'cart' => $cart,
            'total' => $total
        );
    }

    public function getActiveForWarehouseArray(Warehouse $warehouse) {
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare("select p.*, s.color, s.name as status_name, w.name as warehouse_name, 'stock_transfer' as type
	from stock_transfers p 
		left join warehouses w
			on p.receiving_warehouse_id = w.id
		left join status s
			on s.id = p.status_id
	where w.id = :warehouse_id
	and s.name = 'Active'
	union
select p.*, s.color, s.name as status_name, w.name as warehouse_name, 'stock_transfer' as type
	from stock_transfers p 
		left join warehouses w
			on p.departing_warehouse_id = w.id
		left join status s
			on s.id = p.status_id
	where w.id = :warehouse_id
	and s.name = 'Active'");
        $statement->bindValue('warehouse_id', $warehouse->getId());
        $statement->execute();
        return $statement->fetchAll();
    }

    public function getAllForWarehouseArray(Warehouse $warehouse) {
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare("select p.*, s.color, s.name as status_name, w.name as warehouse_name, 'stock_transfer' as type
	from stock_transfers p 
		left join warehouses w
			on p.receiving_warehouse_id = w.id
		left join status s
			on s.id = p.status_id
	where w.id = :warehouse_id
	union
select p.*, s.color, s.name as status_name, w.name as warehouse_name, 'stock_transfer' as type
	from stock_transfers p 
		left join warehouses w
			on p.departing_warehouse_id = w.id
		left join status s
			on s.id = p.status_id
	where w.id = :warehouse_id");
        $statement->bindValue('warehouse_id', $warehouse->getId());
        $statement->execute();
        return $statement->fetchAll();
    }

    public function findAllForChannel(Channel $channel) {
        $transfers = $this->findAll();

        $results = [];
        foreach($transfers as $transfer) {
            $show = false;
            foreach($transfer->getReceivingWarehouse()->getChannels() as $warehouse_channel) {
                if ( $warehouse_channel->getId() == $channel->getId() ) {
                    $show = true;
                }
            }
            foreach($transfer->getDepartingWarehouse()->getChannels() as $warehouse_channel) {
                if ( $warehouse_channel->getId() == $channel->getId() ) {
                    $show = true;
                }
            }

            if ( $show ) {
                $results[] = $transfer;
            }

            return $results;
        }
    }

}
