<?php

namespace WarehouseBundle\Repository;

/**
 * WarehouseInventoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarehouseInventoryRepository extends \Doctrine\ORM\EntityRepository
{
}
